### PR TITLE
Add CUDA option & Meger demos

### PR DESCRIPTION
**Pull request by xiaoweiChen**
I change the code on a old pytorch branch commit.
So the new one is not completely test, I will finish this ASAP.
When I finsh the test, I will update this.

Please Don't merge this before test finish.
Thanks.

1. add --useCUDA option for AlphaPose forward process.
2. merge video, webcam, images demo into one demo scripy.

### CODE REVIEW

**Comment by xiaoweiChen** [comment]
Well, I test all demo mode: image(s), video, webcam.

And I find the latest commit lead some error for demo, I create issue https://github.com/MVIG-SJTU/AlphaPose/issues/237 .

May, #237 should be solved before merge this Pull Request.

**Comment by Jeff-sjtu** [comment]
Sorry, I test the committed code under PyTorch 0.4.1. The padding operation in `cropBox` is necessary, it seems you delete it in your pull request. I will fix this error with a new commitment soon.

**Comment by xiaoweiChen** [comment]
Yes, I comment out the padding operation in my commit. 
If not do that, I can not do video and webcam test. 

En, when you fix the #237, I will merge your commit to my repo, then update this pull request. :)

**Comment by xiaoweiChen** [comment]
@Jeff-sjtu I fix all #237 on Pytorch 0.4.0. You can test my repo, and add the runtime judgement for Pytorch 0.4.1.

**Comment by Jeff-sjtu** [comment]
I have fixed the bug of padding operation in the latest commit. :)

**Comment by xiaoweiChen** [comment]
Well, I merge your latest commit and update this pull request.
The code pass all simple tests.

**Pull request closed without merging**
