### PR TITLE
Update INSTALL.md and setup.py for sorted (alphabetically) in demo script

### PR DESCRIPTION
**Pull request by christw16**
I update for conda and pip install
=> conda install natsort
=> pip install natsort

I will PR windows version for previous version later

Thank you!

### CODE REVIEW

**Comment by Fang-Haoshu** [comment]
Oh I see. Many thanks! How about add it here: https://github.com/MVIG-SJTU/AlphaPose/blob/master/setup.py#L160
instead of in the readme?

**Comment by christw16** [comment]
@Fang-Haoshu  ok, I do it now~

**Comment by christw16** [comment]
@Fang-Haoshu  ok, I have already added in setup.py in line 160

**Comment by Fang-Haoshu** [comment]
Thanks!

**Pull request merged**
