### PR TITLE
Fix bug in tracking visualization.

### PR DESCRIPTION
**Pull request by aFewThings**
fix "TypeError: 'int' object is not iterable" issue.

### CODE REVIEW

**Comment by Fang-Haoshu** [comment]
Hi thanks!

A problem of using range() is that it would mess the ids of the person. Thus range() should not be used here.

With the code here: https://github.com/MVIG-SJTU/AlphaPose/blob/master/alphapose/utils/pPose_nms.py#L121 
the ids should be a list. Can you check if the code I refer to works for you?

Regards

**Comment by aFewThings** [comment]
But it seems human['idx'] returns 'int' object, not a list.
When I print human['idx'], it prints out `1` which is `<class 'int'>`.

**Comment by aFewThings** [comment]
In 118 line of writer.py, `result['result'][i]['idx'] = poseflow_result[i]['idx']`also represents 'int' object.

**Comment by Fang-Haoshu** [comment]
Oh I see. Do you use the --pose_track flag or the --tracking flag?

**Comment by aFewThings** [comment]
Yes, I have used those flags. All of them output the same logs and do some job repeatedly.

**Comment by Fang-Haoshu** [comment]
how about changing the range() to np.array()?

**Comment by aFewThings** [comment]
hmm.. As you said, ids should be a list because human['ids'] is intended to contain tracked persons per frame right?
[In 128 line at poseflow_infer.py](https://github.com/MVIG-SJTU/AlphaPose/blob/d098884735fed86dbbeed02cd16ba0bb00889f5c/PoseFlow/poseflow_infer.py#L128), this code has never been used, is it intended?

**Comment by aFewThings** [comment]
It works :)

**Comment by Fang-Haoshu** [comment]
Thanks

**Pull request merged**
